version: '3'

services:
  db:
    image: nouchka/sqlite3
  tox:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/django-email-builder
    command: tox
    ports:
      - "8000:8000"
    depends_on:
      - db
