# Generated by Django 2.2.10 on 2020-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbuilder',
            name='language',
            field=models.CharField(choices=[('it', 'Italiano')], default='it', help_text='Render template in alternative language', max_length=12, verbose_name='Language'),
        ),
    ]
